# Numpy 

In [18]:
import numpy as np
import math

In [2]:
l = [1,3,4]
np.array(l)


array([1, 3, 4])

In [4]:
# create an array's full of zeroes or ones

print(np.zeros(10))  # create a array of size 10 of zeros
print(np.ones(10))   # create a array of size 10 of ones

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
# creating multi dimensional array
print(np.zeros((2,3)))
print(np.zeros((2,3,2)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [9]:
a = np.array([[1,2,3],[4,5,6],[1,2,3],[4,5,6]])
print(a[0])
print(a[:,2:4])

[1 2 3]
[[3]
 [6]
 [3]
 [6]]


In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+2)
print(a+b)
print(b*a)
print(b*10)
print(a**b)
print(b//a)

[3 4 5]
[5 7 9]
[ 4 10 18]
[40 50 60]
[  1  32 729]
[4 2 2]


In [15]:
print(a.mean())
print(b.sum())

2.0
15


In [19]:
a = np.array([1,2,3])
b = np.array([4,5,6])

d = ((a-b) ** 2).sum()
print(math.sqrt(d))

5.196152422706632


In [20]:
x = np.array([1,2,3,4,5,6])
((x - x.mean()) ** 2).sum()

17.5

In [22]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[10,20],[30,40]])

#dot product of these two arrays
a1.dot(a2)

array([[ 70, 100],
       [150, 220]])